# fly.toml app configuration file generated for smashmate-alert on 2024-08-25T03:01:49+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smashmate-alert'
primary_region = 'nrt'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
